---
- name: OpenShift crashing pod
  hosts: all
  sources:
    - ansible.eda.alertmanager:
        host: 0.0.0.0
        port: 5001

  rules:
    - name: Crashing pod detected
      condition: event.alert.labels.alertname == "EDA_PodCrashLooping"
      action:
        run_job_template:
          name: "health_checks"
          organization: "Default"
          post_events: true
          
    - name: Image pull error detected
      condition: event.alert.labels.alertname == "EDA_PodImagePullBackOff"
      action:
        run_job_template:
          name: "image_pullbackoff_checks"
          organization: "Default"
          post_events: true
